---
name: make
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install xsv
      - uses: actions/checkout@v2
      - run: wget -nv https://yegor256.github.io/plum/index.xml -O before.xml
      - uses: yegor256/plum@master
        env:
          BEFORE: before.xml
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      - run: mkdir gh-pages
      - run: cp target/index.html gh-pages
      - run: cp target/index.xml gh-pages
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
